name: Build and Deploy image for products

on:
  push:
    paths:
      - 'Products/**'
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug — Show current path and files
        run: |
          echo "WORKDIR: $(pwd)"
          echo "Directory tree:"
          find . -type f

      - name: Debug — Docker version
        run: docker --version

      - name: Debug — Check user permissions
        run: whoami && groups

      - name: Debug — Show contents of ./Products
        run: ls -l ./Products || echo "Products dir not found!"

      - name: Debug — Print Dockerfile
        run: cat ./Products/Dockerfile || echo "Dockerfile not found!"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Update this if your Products path is not found
          context: ./Products
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/products:latest
